/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_ingreso_vehicular;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import conexion.ConexioMySQL;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author user
 */
public class Registros_ingresantes_vehiculos extends javax.swing.JInternalFrame {

    private ConexioMySQL conexion;

    Calendar cal;
    String descripcion, year;

    /**
     * Creates new form TABLA
     */
    public Registros_ingresantes_vehiculos() {
        initComponents();

        cal = Calendar.getInstance();
        year = Integer.toString(cal.get(Calendar.YEAR));
        fecha_v.setDate(cal.getTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DNIPROPIETARIO = new javax.swing.JTextField();
        TXTPROPIETARIO = new javax.swing.JTextField();
        RBSI = new javax.swing.JRadioButton();
        RBNO = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTDNICONDUCTOR = new javax.swing.JTextField();
        TXTCORREOCONDUCTOR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTCONDUCTOR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTTELEFONOCONDUCTOR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TXTCOLOR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TXTPLACAV = new javax.swing.JTextField();
        TXTPLACAA = new javax.swing.JTextField();
        NUMSERIE = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        NUMVIN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        COMBOSEDE = new javax.swing.JComboBox<>();
        TXTMARCA = new javax.swing.JTextField();
        TXTDESCRIPCION = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fecha_v = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        combotipov = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        B_REGISTRAR = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lblcodigo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("DATOS DEL CONDUCTOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Ingresantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(DNIPROPIETARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, 30));
        jPanel1.add(TXTPROPIETARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 260, 30));

        buttonGroup1.add(RBSI);
        RBSI.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        RBSI.setForeground(new java.awt.Color(51, 255, 51));
        RBSI.setText("SI");
        jPanel1.add(RBSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        buttonGroup1.add(RBNO);
        RBNO.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        RBNO.setForeground(new java.awt.Color(0, 255, 0));
        RBNO.setText("NO");
        RBNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNOActionPerformed(evt);
            }
        });
        jPanel1.add(RBNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefono del conductor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Correo del conductor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 190, -1));
        jPanel1.add(TXTDNICONDUCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 260, 30));
        jPanel1.add(TXTCORREOCONDUCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 260, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DNI del conductor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, -1));

        TXTCONDUCTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCONDUCTORActionPerformed(evt);
            }
        });
        jPanel1.add(TXTCONDUCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 260, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Conductor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        TXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDActionPerformed(evt);
            }
        });
        jPanel1.add(TXTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 260, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DNI del Propietario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Propietario del vehiculo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        jPanel1.add(TXTTELEFONOCONDUCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 260, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Lincencia de Conducir");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 510, 357));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL VEHICULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 204))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel9.setText("Placa Vigente ");

        jLabel14.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel14.setText("Nº Vin:");

        jLabel15.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel15.setText("Marca");

        jLabel16.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel16.setText("SEDE:");

        jLabel18.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel18.setText("Color");

        jLabel20.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel20.setText("Nº Serie: ");

        NUMVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMVINActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel11.setText("Placa Anterior ");

        COMBOSEDE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR SEDE:", "Tumbes", "Piura", "Lambayeque", "Cajamarca", "La Libertad", "Lima", "Junin", "Cerro de Pasco", "Huanuco", "SELECCIONAR SEDE:", "Huancavelica", "Ayacucho", "Ica", "Arequipa", "Moquegua", "Tacna", "Cusco", "Madre de Dios", "Apurimac" }));
        COMBOSEDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOSEDEActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setText("Descripcion");

        jLabel12.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel12.setText("FECHA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(51, 51, 51))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_v, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTDESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTPLACAV, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTPLACAA, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUMVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COMBOSEDE, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCOLOR, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUMSERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPLACAA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXTPLACAV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(NUMVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMBOSEDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TXTCOLOR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(NUMSERIE, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(TXTDESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 6, 400, 470));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE VEHICULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        combotipov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR:", "Motocicletas", "Motocarro", "Mototriciclo", "Automovil", "Camioneta", "Bus", "Bicicleta", "Moto electrica" }));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen1.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/coche1.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bicycle_icon_160403-removebg-preview.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rickshaw-tuk-icon-image-260nw-736553407-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(29, 29, 29)
                .addComponent(combotipov, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel24)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(combotipov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 466, -1));

        B_REGISTRAR.setBackground(new java.awt.Color(0, 204, 51));
        B_REGISTRAR.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        B_REGISTRAR.setText("REGISTRAR");
        B_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_REGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(B_REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 100, -1));

        lblcodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcodigoMouseClicked(evt);
            }
        });
        getContentPane().add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, 240, 230));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, -40, -1, -1));

        jButton2.setText("IMPRIMIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limpiarCajas() {

        TXTID.setText("");
        TXTPROPIETARIO.setText("");
        DNIPROPIETARIO.setText("");
        TXTCONDUCTOR.setText("");
        TXTDNICONDUCTOR.setText("");
        TXTCORREOCONDUCTOR.setText("");
        TXTTELEFONOCONDUCTOR.setText("");
        TXTMARCA.setText("");
        TXTPLACAA.setText("");
        NUMVIN.setText("");
        TXTCOLOR.setText("");
        NUMSERIE.setText("");
        TXTDESCRIPCION.setText("");
        TXTPLACAV.setText("");
    }

    void codigosclientes() {
        int j;
        int cont = 1;
        String num = "";
        String c = "";

        String SQL = "select max(cod_cli) from cliente";

        try {
            Statement st = Con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                lblcodigo.setText("VI0001");
            } else {
                char r1 = c.charAt(2);
                char r2 = c.charAt(3);
                char r3 = c.charAt(4);
                char r4 = c.charAt(5);
                String r = "";
                r = "" + r1 + r2 + r3 + r4;

                j = Integer.parseInt(r);
                GenerarCodigos gen = new GenerarCodigos();
                gen.generar(j);
                lblcodigo.setText("VV" + gen.serie());

            }

        } catch (SQLException ex) {
            Logger.getLogger(Registros_ingresantes_vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void RBNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBNOActionPerformed

    private void TXTCONDUCTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCONDUCTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCONDUCTORActionPerformed

    private void NUMVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMVINActionPerformed

    private void COMBOSEDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOSEDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOSEDEActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Salio del Formulario Registrar Equipos de Computo ");
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void B_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_REGISTRARActionPerformed
        // TODO add your handling code here:
        conexion = new ConexioMySQL();
        conexion.ConectarBasedeDatos();

        String id = TXTID.getText();
        String pro = TXTPROPIETARIO.getText();
        String dnipro = DNIPROPIETARIO.getText();
        String conductor = TXTCONDUCTOR.getText();
        String dnicon = TXTDNICONDUCTOR.getText();
        String correocon = TXTCORREOCONDUCTOR.getText();
        String telefonocon = TXTTELEFONOCONDUCTOR.getText();
        String licencia = RBNO.isSelected() ? "NO" : "SI";

        String tipodevehiculo = combotipov.getSelectedItem().toString();
        String marca = TXTMARCA.getText();
        String placaan = TXTPLACAA.getText();
        String placavigente = TXTPLACAV.getText();
        String numerovin = NUMVIN.getText();
        String sede = COMBOSEDE.getSelectedItem().toString();
        String color = TXTCOLOR.getText();
        String serie = NUMSERIE.getText();
        String des = TXTDESCRIPCION.getText();

//       DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
//    Date fecha_venta = resultado.getDate("fecha_venta");
//    String fechaFormateada = dateFormat.format(fecha_venta);
        try {
            // Insertar datos en la base de datos
            String conSql = "INSERT INTO tabla_vehiculos(Id_vehiculos,propietario_vehiculo,dni_propietario,conductor,dni_conductor,correo,telefono,licencia,tipo_vehiculo,marca,placa_anterior,placa_vigente,Num_vin,sede,color,serie, descripcion,fecha_registro) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conexion.getConnection().prepareStatement(conSql);

            Calendar cal = Calendar.getInstance();
            cal.setTime(fecha_v.getDate());
            int day = cal.get(Calendar.DAY_OF_MONTH);
            int mes = cal.get(Calendar.MONTH);
            int year = cal.get(Calendar.YEAR);
            String daystr;
            if (day <= 9) {
                daystr = '0' + String.valueOf(day);
            } else {
                daystr = String.valueOf(day);
            }

            String messtr;
            mes = mes + 1;
            if (mes <= 9) {
                messtr = '0' + String.valueOf(mes);
            } else {
                messtr = String.valueOf(mes);
            }

            String yearstr = String.valueOf(year);
            String fecha_registro = yearstr + "-" + messtr + "-" + daystr;

            pst.setString(1, id);
            pst.setString(2, pro);
            pst.setString(3, dnipro);
            pst.setString(4, conductor);
            pst.setString(5, dnicon);
            pst.setString(6, correocon);
            pst.setString(7, telefonocon);
            pst.setString(8, licencia);
            pst.setString(9, tipodevehiculo);
            pst.setString(10, marca);
            pst.setString(11, placaan);
            pst.setString(12, placavigente);
            pst.setString(13, numerovin);
            pst.setString(14, sede);
            pst.setString(15, color);
            pst.setString(16, serie);
            pst.setString(17, des);
            pst.setString(18, fecha_registro);
            pst.execute();

            JOptionPane.showMessageDialog(this, "Datos guardado exitosamente.");
////////////////
            String contenidoQR = generarContenidoQR(id, pro, dnipro, conductor, dnicon, correocon, telefonocon, licencia,
                    tipodevehiculo, marca, placaan, placavigente, numerovin, sede, color, serie, des, fecha_registro);

            // Generar el código QR y mostrarlo en el JLabel
            mostrarCodigoQR(lblcodigo, contenidoQR);

            limpiarCajas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error al Registrar Datos");
            limpiarCajas();

        }
    }//GEN-LAST:event_B_REGISTRARActionPerformed

    private String generarContenidoQR(String id, String pro, String dnipro, String conductor, String dnicon,
            String correocon, String telefonocon, String licencia, String tipodevehiculo,
            String marca, String placaan, String placavigente, String numerovin, String sede,
            String color, String serie, String des, String fecha_registro) {
        // Generar el contenido para el código QR con los datos que quieras incluir
        return "ID: " + id + "\nPropietario: " + pro + "\nDNI Propietario: " + dnipro + "\nConductor: " + conductor
                + "\nDNI Conductor: " + dnicon + "\nCorreo Conductor: " + correocon + "\nTeléfono Conductor: "
                + telefonocon + "\nLicencia: " + licencia + "\nTipo de Vehículo: " + tipodevehiculo + "\nMarca: "
                + marca + "\nPlaca Anterior: " + placaan + "\nPlaca Vigente: " + placavigente + "\nNúmero VIN: "
                + numerovin + "\nSede: " + sede + "\nColor: " + color + "\nNúmero de Serie: " + serie
                + "\nDescripción: " + des + "\nFECHA DE INGRESO: " + fecha_registro;

    }

    private void mostrarCodigoQR(JLabel label, String content) throws WriterException {
        int size = 250; // Tamaño del código QR

        Hashtable<EncodeHintType, ErrorCorrectionLevel> hintMap = new Hashtable<>();
        hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);

        // Configurar el generador de código QR
        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        com.google.zxing.common.BitMatrix bitMatrix = qrCodeWriter.encode(content, BarcodeFormat.QR_CODE, size, size, hintMap);

        // Crear la imagen del código QR
        int width = bitMatrix.getWidth();
        int height = bitMatrix.getHeight();
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                image.setRGB(x, y, bitMatrix.get(x, y) ? Color.BLACK.getRGB() : Color.WHITE.getRGB());
            }
        }
        ImageIcon icon = new ImageIcon(image);
        label.setIcon(icon);

    }

//     public BufferedImage generarCodigoQR(String texto) {
//        int ancho = 300;
//        int alto = 300;
//
//        try {
//            // Configuración para generar el código QR
//            MultiFormatWriter writer = new MultiFormatWriter();
//            BitMatrix matriz = writer.encode(texto, BarcodeFormat.QR_CODE, ancho, alto);
//
//            // Convertir la matriz en una imagen BufferedImage
//            BufferedImage imagen = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_RGB);
//            for (int i = 0; i < ancho; i++) {
//                for (int j = 0; j < alto; j++) {
//                    int color = matriz.get(i, j) ? 0xFF000000 : 0xFFFFFFFF;
//                    imagen.setRGB(i, j, color);
//                }
//            }
//
//            return imagen;
//        } catch (Exception e) {
//            e.printStackTrace();
//            return null;
//        }
//    }
//
//    public void asignarCodigoQR(BufferedImage codigoQR, JLabel labelCodigoQR) {
//        if (codigoQR != null) {
//            Image imagenEscalada = codigoQR.getScaledInstance(labelCodigoQR.getWidth(), labelCodigoQR.getHeight(), Image.SCALE_SMOOTH);
//            ImageIcon icono = new ImageIcon(imagenEscalada);
//            labelCodigoQR.setIcon(icono);
//        }
//    }
//    
//    
//    
//    
//    
//    
////    public void MostrarCodigoQR() {
////        initializeUI(); // Método para inicializar la interfaz gráfica
////        BufferedImage codigoQR = generarCodigoQR("¡Hola! Esto es un código QR generado en Java con ZXing.");
////        mostrarCodigoQR(codigoQR);
////    }
////    
////   
////      private void initializeUI() {
////        setTitle("Mostrar Código QR"); // Título de la ventana
////        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Cierra la aplicación al cerrar la ventana
////        setLayout(new BorderLayout()); // Establece el diseño de la ventana como BorderLayout
////
////        lblcodigo = new JLabel(); // Crea un JLabel para mostrar el código QR
////        add(lblcodigo, BorderLayout.CENTER); // Agrega el JLabel al centro de la ventana
////
////        pack(); // Ajusta el tamaño de la ventana automáticamente
////        setLocationRelativeTo(null); // Centra la ventana en la pantalla
////        setVisible(true); // Hace visible la ventana
////    }
////      
////      
////    
////     public BufferedImage generarCodigoQR(String texto) {
//        int ancho = 300;
//        int alto = 300;
//
//        try {
//            // Configuración para generar el código QR
//            MultiFormatWriter writer = new MultiFormatWriter();
//            BitMatrix matriz = writer.encode(texto, BarcodeFormat.QR_CODE, ancho, alto);
//
//            // Convertir la matriz en una imagen BufferedImage
//            BufferedImage imagen = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_RGB);
//            for (int i = 0; i < ancho; i++) {
//                for (int j = 0; j < alto; j++) {
//                    int color = matriz.get(i, j) ? 0xFF000000 : 0xFFFFFFFF; // Asigna el color según la matriz
//                    imagen.setRGB(i, j, color); // Establece el color en la imagen
//                }
//            }
//            
//             System.out.println("¡Código QR generado correctamente!"); // Mensaje de éxito en la consola
//       // return imagen; // Devuelve la imagen del código QR generada
//
//            return imagen; // Devuelve la imagen del código QR generada
//        } catch (Exception e) {
//            e.printStackTrace();
//            
//            System.out.println("¡error al generar Código QR !");
//            return null;
//            
//        }
//    }
//     
//     
//     public void mostrarCodigoQR(BufferedImage codigoQR) {
//        if (codigoQR != null) {
//            // Escalar la imagen para ajustarla al tamaño del JLabel
//            Image imagenEscalada = codigoQR.getScaledInstance(lblcodigo.getWidth(), lblcodigo.getHeight(), Image.SCALE_SMOOTH);
//
//            // Crear un ImageIcon a partir de la imagen escalada y asignarlo al JLabel
//            ImageIcon icono = new ImageIcon(imagenEscalada);
//            lblcodigo.setIcon(icono); // Establece el código QR en el JLabel
//        }
//    } 
//    
//    
//    
//    public  void GenerarCodigoQR()
//{
//    
//     String texto = "¡Hola! Esto es un código QR generado en Java con ZXing.";
//
//        // Directorio donde se guardará el archivo PNG del código QR
//        String rutaArchivoQR = 
//         "C:\\Users\\heyner.rivas\\Documents\\qrcodigoQR.png";
//        
//        
//
//        int ancho = 300;
//        int alto = 300;
//
//        try {
//            // Configuración para generar el código QR
//            MultiFormatWriter writer = new MultiFormatWriter();
//            BitMatrix matriz = writer.encode(texto, BarcodeFormat.QR_CODE, ancho, alto);
//
//            // Convertir la matriz en una imagen BufferedImage
//            BufferedImage imagen = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_RGB);
//            for (int i = 0; i < ancho; i++) {
//                for (int j = 0; j < alto; j++) {
//                    Color color = matriz.get(i, j) ? Color.BLACK : Color.WHITE;
//                    imagen.setRGB(i, j, color.getRGB());
//                }
//            }
//
//            // Guardar la imagen del código QR en un archivo
//            File archivo = new File(rutaArchivoQR);
//            ImageIO.write(imagen, "png", archivo);
//
//            System.out.println("¡Código QR generado correctamente!");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//     String texto = "¡Hola! Esto es un código QR generado en Java con ZXing.";
//
//        // Directorio donde se guardará el archivo PNG del código QR
//        String rutaArchivoQR = "codigoQR.png";
//
//        int ancho = 300;
//        int alto = 300;
//
//        try {
//            // Configuración para generar el código QR
//            com.google.zxing.Writer writer = new QRCodeWriter();
//            BitMatrix matriz = writer.encode(texto, BarcodeFormat.QR_CODE, ancho, alto);
//
//            // Crear el archivo de imagen del código QR
//            Path ruta = FileSystems.getDefault().getPath(rutaArchivoQR);
//            MatrixToImageWriter.writeToPath(matriz, "PNG", ruta);
//
//            System.out.println("¡Código QR generado correctamente!");
//        } catch (WriterException e) {
//            e.printStackTrace();
//        }
//	ByteArrayOutputStream out=QRCode.from(this.TXTID.getText()).to(ImageType.PNG).stream();
//	ImageIcon imageIcon=new ImageIcon(out.toByteArray());
//	this.lblcodigo.setIcon(imageIcon);

    private void TXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDActionPerformed

    private void lblcodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcodigoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcodigoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            // Obtener la imagen del código QR desde el JLabel
            ImageIcon icon = (ImageIcon) lblcodigo.getIcon();
            Image image = icon.getImage();

            // Crear un objeto PrinterJob
            PrinterJob job = PrinterJob.getPrinterJob();

            // Definir el contenido a imprimir
            job.setPrintable((graphics, pageFormat, pageIndex) -> {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) graphics;
                g2.drawImage(image, 100, 100, null); // Ajusta las coordenadas de acuerdo a tu necesidad

                return Printable.PAGE_EXISTS;
            });

            // Mostrar el diálogo de impresión
            if (job.printDialog()) {
                job.print();
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Error al imprimir: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_REGISTRAR;
    private javax.swing.JComboBox<String> COMBOSEDE;
    private javax.swing.JTextField DNIPROPIETARIO;
    private javax.swing.JTextField NUMSERIE;
    private javax.swing.JTextField NUMVIN;
    private javax.swing.JRadioButton RBNO;
    private javax.swing.JRadioButton RBSI;
    private javax.swing.JTextField TXTCOLOR;
    private javax.swing.JTextField TXTCONDUCTOR;
    private javax.swing.JTextField TXTCORREOCONDUCTOR;
    private javax.swing.JTextField TXTDESCRIPCION;
    private javax.swing.JTextField TXTDNICONDUCTOR;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTMARCA;
    private javax.swing.JTextField TXTPLACAA;
    private javax.swing.JTextField TXTPLACAV;
    private javax.swing.JTextField TXTPROPIETARIO;
    private javax.swing.JTextField TXTTELEFONOCONDUCTOR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combotipov;
    private com.toedter.calendar.JDateChooser fecha_v;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblcodigo;
    // End of variables declaration//GEN-END:variables
ConexioMySQL Con = new ConexioMySQL();

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
